name: My Custom Action

on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 23f3002639@ds.study.iitm.ac.in
        run: echo "Hello, world! This action was triggered successfully."
